name: ci

on:
    pull_request:
    push:
        branches: [main]

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        name: pre-commit
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4
        - uses: pre-commit/action@v3.0.0

    build-book:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'
            cache: 'pip'

        - name: Install dependencies
          run: pip install -r requirements-dev.txt

        - name: Build the book
          run: make book

        # Push the book's HTML to github-pages
        - name: GitHub Pages action
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: book/_build/html
